export default (args: { model: string; op: string; specs: string; customReturn?: string; modelMeta?: any }) => `
// Generated by nuxt-modelator
import { makeHandler } from '#nuxt-modelator/runtime/executor'
export default makeHandler(
  ${JSON.stringify(args.model)}, 
  ${JSON.stringify(args.op)}, 
  ${args.specs}, 
  ${args.customReturn ? JSON.stringify(args.customReturn) : "undefined"},
  ${JSON.stringify(args.modelMeta || {})}
)
`;
