import "reflect-metadata";
import { pushPropTransform } from "../../registry.js";

export function Id(autogenerated: boolean = true): PropertyDecorator {
        return (target: any, propertyKey: string | symbol) => {
                pushPropTransform(target, propertyKey as string, {
                        kind: "mongoId",
                        config: { autogenerated },
                });
        };
}
