version: "3.8"

services:
    mongodb:
        image: mongo:7.0-jammy
        container_name: nuxt-modelator-mongo
        restart: unless-stopped
        ports:
            - "27018:27017"
        environment:
            MONGO_INITDB_ROOT_USERNAME: modelator
            MONGO_INITDB_ROOT_PASSWORD: modelator123
            MONGO_INITDB_DATABASE: nuxt-modelator-demo
        volumes:
            - mongodb_data:/data/db
            - ./mongo-init:/docker-entrypoint-initdb.d
        networks:
            - modelator-network
        healthcheck:
            test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 30s

    mongo-express:
        image: mongo-express:1.0.0-alpha
        container_name: nuxt-modelator-mongo-express
        restart: unless-stopped
        ports:
            - "8081:8081"
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: modelator
            ME_CONFIG_MONGODB_ADMINPASSWORD: modelator123
            ME_CONFIG_MONGODB_URL: mongodb://modelator:modelator123@mongodb:27017/
            ME_CONFIG_BASICAUTH_USERNAME: admin
            ME_CONFIG_BASICAUTH_PASSWORD: admin123
        depends_on:
            mongodb:
                condition: service_healthy
        networks:
            - modelator-network

volumes:
    mongodb_data:
        driver: local

networks:
    modelator-network:
        driver: bridge
